name: katura_system
description: "高級弁当宅配専門店（岡崎弁当）向け社内業務システム"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.11.0
  cloud_firestore: ^6.6.0
  printing: ^5.13.0
  pdf: ^3.11.1
  table_calendar: ^3.1.2
  google_maps_flutter: ^2.6.0
  path: ^1.9.0
  path_provider: ^2.1.1
  sqlite3: ^3.5.0
  sqlite3_flutter_libs: ^0.5.0
  html: ^0.15.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/navi_database.db

