// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU8PnSULiVu4_JyiqSXQuanD21u0fHM6Q',
    appId: '1:698860566876:web:44c7e7a8fecb23016fa999',
    messagingSenderId: '698860566876',
    projectId: 'fir-2d6ea',
    authDomain: 'fir-2d6ea.firebaseapp.com',
    storageBucket: 'fir-2d6ea.firebasestorage.app',
    measurementId: 'G-3W33JLLJRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBujgkbXlSkWIhDMCqp1nmrIJrUOF3P4_Y',
    appId: '1:698860566876:android:98ca0d0b6b26f7386fa999',
    messagingSenderId: '698860566876',
    projectId: 'fir-2d6ea',
    storageBucket: 'fir-2d6ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8hC_gZ0CLmeAYlcjWEVjApzS7piVQcEI',
    appId: '1:698860566876:ios:a26c0d67c2e32c586fa999',
    messagingSenderId: '698860566876',
    projectId: 'fir-2d6ea',
    storageBucket: 'fir-2d6ea.firebasestorage.app',
    iosBundleId: 'com.katura.katuraSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8hC_gZ0CLmeAYlcjWEVjApzS7piVQcEI',
    appId: '1:698860566876:ios:a26c0d67c2e32c586fa999',
    messagingSenderId: '698860566876',
    projectId: 'fir-2d6ea',
    storageBucket: 'fir-2d6ea.firebasestorage.app',
    iosBundleId: 'com.katura.katuraSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU8PnSULiVu4_JyiqSXQuanD21u0fHM6Q',
    appId: '1:698860566876:web:59fdc88c79cb48b26fa999',
    messagingSenderId: '698860566876',
    projectId: 'fir-2d6ea',
    authDomain: 'fir-2d6ea.firebaseapp.com',
    storageBucket: 'fir-2d6ea.firebasestorage.app',
    measurementId: 'G-8T673QR5WF',
  );
}
