// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const String _generalApiKey = 'AIzaSyAGqDBjV4ounHAldaU-N8wBZqc_aWq4FMM';
  static const String _webApiKey = 'AIzaSyDLNOudyf0exTSAh1_37ccownObPfWZxro';

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _webApiKey,
    appId: '1:639111103872:web:d6138be46fc39a6af6ed65',
    messagingSenderId: '639111103872',
    projectId: 'katura-system-dfc8b',
    authDomain: 'katura-system-dfc8b.firebaseapp.com',
    storageBucket: 'katura-system-dfc8b.firebasestorage.app',
    measurementId: 'G-WV3WXWWDDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: _generalApiKey,
    appId: '1:639111103872:android:f67e8da9026810f2f6ed65',
    messagingSenderId: '639111103872',
    projectId: 'katura-system-dfc8b',
    storageBucket: 'katura-system-dfc8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: _generalApiKey,
    appId: '1:639111103872:ios:f0aa28d591b44a72f6ed65',
    messagingSenderId: '639111103872',
    projectId: 'katura-system-dfc8b',
    storageBucket: 'katura-system-dfc8b.firebasestorage.app',
    iosBundleId: 'com.katura.katuraSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: _generalApiKey,
    appId: '1:639111103872:ios:f0aa28d591b44a72f6ed65',
    messagingSenderId: '639111103872',
    projectId: 'katura-system-dfc8b',
    storageBucket: 'katura-system-dfc8b.firebasestorage.app',
    iosBundleId: 'com.katura.katuraSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: _webApiKey,
    appId: '1:639111103872:web:d6138be46fc39a6af6ed65',
    messagingSenderId: '639111103872',
    projectId: 'katura-system-dfc8b',
    authDomain: 'katura-system-dfc8b.firebaseapp.com',
    storageBucket: 'katura-system-dfc8b.firebasestorage.app',
    measurementId: 'G-WV3WXWWDDW',
  );
}
